name: Build WF

on: 
  push:
    branches:
      - main  # Yahan space zaroori hai

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven Build
        # Wahi skip flags jo humne Jenkins mein use kiye the
        run: mvn clean install -DskipTests -Dnohttp.skip=true -Dcheckstyle.skip

  Testing:
    runs-on: ubuntu-latest
    needs: Build  # Build ka 'B' capital rakha hai (Matching job name)
    steps:
      - name: Code checkout
        uses: actions/checkout@v16

      - name: Run tests on main branch
        run: Maven test -Dnohttp.skip=true -Dcheckstyle.skip

      - name: Checkstyle
        # Agar tu asaliyat mein checkstyle run karna chahta hai
        run: mvn checkstyle:checkstyle -Dnohttp.skip=true