name: Build WF

on: 
  push:
    branches:
      - main  # Yahan space fix kar diya

jobs:
  Build:  # Ye job ka naam hai
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven Build
        # vProfile ke liye 'mvn install' aur checkstyle skip flags
        run: mvn clean install -DskipTests -Dnohttp.skip=true -Dcheckstyle.skip

  Testing:
    runs-on: ubuntu-latest
    needs: Build  # Yahan 'B' capital kar diya taaki upar wale job se match kare
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Run tests
        # Tests run karte waqt bhi security checks skip kar rahe hain
        run: mvn test -Dnohttp.skip=true -Dcheckstyle.skip

      - name: Checkstyle Report
        # Agar sirf report check karni hai
        run: mvn checkstyle:checkstyle -Dnohttp.skip=true